application: intense-terra-821
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Endpoints handler
- url: /_ah/spi/.*
  script: main.app


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0


#libraries:
#- name: webapp2
#  version: "2.5.2"
